services:
    app:
        container_name: app
        image: app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
            - "3000:3000"
